In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [68]:
df = pd.read_csv('super.csv')
df

,Invoice ID,Branch,Yangon,Naypyitaw,Mandalay,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
0,750-67-8428,A,1,0,0,Normal,Male,Health and beauty,74.69,7,26.1415,NaN,1/5/2019,13:08,Ewallet,9.1
1,226-31-3081,C,0,1,0,Normal,Male,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,9.6
2,631-41-3108,A,1,0,0,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,NaN,489.0480,1/27/2019,8 - 30 PM,Ewallet,8.4
4,373-73-7910,A,1,0,0,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,861-77-0145,C,0,1,0,Member,Male,Electronic accessories,81.97,10,40.9850,860.6850,3/3/2019,14:30,Cash,9.2
1002,479-26-8945,B,0,0,1,Member,Female,Sports and travel,16.49,2,1.6490,34.6290,2/5/2019,11:32,Ewallet,4.6
1003,210-67-5886,C,0,1,0,Member,Female,Health and beauty,98.21,3,14.7315,309.3615,2/5/2019,10:41,Credit card,7.8
1004,227-78-1148,B,0,0,1,Normal,Female,Fashion accessories,72.84,7,25.4940,535.3740,2/15/2019,12:44,Cash,8.4
1005,645-44-1170,A,1,0,0,Member,Male,Home and lifestyle,58.07,9,26.1315,548.7615,1/19/2019,20:07,Ewallet,4.3

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice ID     1006 non-null   object
 1   Branch         1006 non-null   object
 2   Yangon         1006 non-null   int64
 3   Naypyitaw      1006 non-null   int64
 4   Mandalay       1006 non-null   int64
 5   Customer type  1006 non-null   object
 6   Gender         1006 non-null   object
 7   Product line   1006 non-null   object
 8   Unit price     1006 non-null   object
 9   Quantity       1006 non-null   int64
 10  Tax 5%         997 non-null    float64
 11  Total          1003 non-null   float64
 12  Date           1006 non-null   object
 13  Time           1006 non-null   object
 14  Payment        1006 non-null   object
 15  Rating         1006 non-null   float64
dtypes: float64(3), int64(4), object(9)
memory usage: 125.9+ KB

Rename the columns

In [70]:
df.rename(columns={'Invoice ID':'Invoice_ID','Customer type':'Customer_type','Product line':'Product_line','Unit price':'Unit_price','Quantity':'Quantity','Tax 5%':'Tax'},inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice_ID     1006 non-null   object
 1   Branch         1006 non-null   object
 2   Yangon         1006 non-null   int64
 3   Naypyitaw      1006 non-null   int64
 4   Mandalay       1006 non-null   int64
 5   Customer_type  1006 non-null   object
 6   Gender         1006 non-null   object
 7   Product_line   1006 non-null   object
 8   Unit_price     1006 non-null   object
 9   Quantity       1006 non-null   int64
 10  Tax            997 non-null    float64
 11  Total          1003 non-null   float64
 12  Date           1006 non-null   object
 13  Time           1006 non-null   object
 14  Payment        1006 non-null   object
 15  Rating         1006 non-null   float64
dtypes: float64(3), int64(4), object(9)
memory usage: 125.9+ KB

clean the format of the column('Unit_price') to convert to float

In [71]:
df['Unit_price']=df['Unit_price'].str.replace(' USD','')
df['Unit_price']=df['Unit_price'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice_ID     1006 non-null   object
 1   Branch         1006 non-null   object
 2   Yangon         1006 non-null   int64
 3   Naypyitaw      1006 non-null   int64
 4   Mandalay       1006 non-null   int64
 5   Customer_type  1006 non-null   object
 6   Gender         1006 non-null   object
 7   Product_line   1006 non-null   object
 8   Unit_price     1006 non-null   float64
 9   Quantity       1006 non-null   int64
 10  Tax            997 non-null    float64
 11  Total          1003 non-null   float64
 12  Date           1006 non-null   object
 13  Time           1006 non-null   object
 14  Payment        1006 non-null   object
 15  Rating         1006 non-null   float64
dtypes: float64(4), int64(4), object(8)
memory usage: 125.9+ KB

calculate the tax column to fill the null values

In [72]:
df['Tax']=df['Unit_price']*df['Quantity']*0.05
df.head()

,Invoice_ID,Branch,Yangon,Naypyitaw,Mandalay,Customer_type,Gender,Product_line,Unit_price,Quantity,Tax,Total,Date,Time,Payment,Rating
0,750-67-8428,A,1,0,0,Normal,Male,Health and beauty,74.69,7,26.1415,NaN,1/5/2019,13:08,Ewallet,9.1
1,226-31-3081,C,0,1,0,Normal,Male,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,9.6
2,631-41-3108,A,1,0,0,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8 - 30 PM,Ewallet,8.4
4,373-73-7910,A,1,0,0,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,5.3

Calculate the Total column to clear the null values

In [73]:
df['Total']=df['Unit_price']*df['Quantity']+df['Tax']
df.head()

,Invoice_ID,Branch,Yangon,Naypyitaw,Mandalay,Customer_type,Gender,Product_line,Unit_price,Quantity,Tax,Total,Date,Time,Payment,Rating
0,750-67-8428,A,1,0,0,Normal,Male,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,9.1
1,226-31-3081,C,0,1,0,Normal,Male,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,9.6
2,631-41-3108,A,1,0,0,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8 - 30 PM,Ewallet,8.4
4,373-73-7910,A,1,0,0,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,5.3

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice_ID     1006 non-null   object
 1   Branch         1006 non-null   object
 2   Yangon         1006 non-null   int64
 3   Naypyitaw      1006 non-null   int64
 4   Mandalay       1006 non-null   int64
 5   Customer_type  1006 non-null   object
 6   Gender         1006 non-null   object
 7   Product_line   1006 non-null   object
 8   Unit_price     1006 non-null   float64
 9   Quantity       1006 non-null   int64
 10  Tax            1006 non-null   float64
 11  Total          1006 non-null   float64
 12  Date           1006 non-null   object
 13  Time           1006 non-null   object
 14  Payment        1006 non-null   object
 15  Rating         1006 non-null   float64
dtypes: float64(4), int64(4), object(8)
memory usage: 125.9+ KB

clean the time column

In [75]:
df['Time']= df['Time'].str.replace(' - ',':')
df

,Invoice_ID,Branch,Yangon,Naypyitaw,Mandalay,Customer_type,Gender,Product_line,Unit_price,Quantity,Tax,Total,Date,Time,Payment,Rating
0,750-67-8428,A,1,0,0,Normal,Male,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,9.1
1,226-31-3081,C,0,1,0,Normal,Male,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,9.6
2,631-41-3108,A,1,0,0,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:30 PM,Ewallet,8.4
4,373-73-7910,A,1,0,0,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,861-77-0145,C,0,1,0,Member,Male,Electronic accessories,81.97,10,40.9850,860.6850,3/3/2019,14:30,Cash,9.2
1002,479-26-8945,B,0,0,1,Member,Female,Sports and travel,16.49,2,1.6490,34.6290,2/5/2019,11:32,Ewallet,4.6
1003,210-67-5886,C,0,1,0,Member,Female,Health and beauty,98.21,3,14.7315,309.3615,2/5/2019,10:41,Credit card,7.8
1004,227-78-1148,B,0,0,1,Normal,Female,Fashion accessories,72.84,7,25.4940,535.3740,2/15/2019,12:44,Cash,8.4
1005,645-44-1170,A,1,0,0,Member,Male,Home and lifestyle,58.07,9,26.1315,548.7615,1/19/2019,20:07,Ewallet,4.3

clean the time column

In [76]:
df['Time']=pd.to_datetime(df['Time']).dt.time
df.head()

,Invoice_ID,Branch,Yangon,Naypyitaw,Mandalay,Customer_type,Gender,Product_line,Unit_price,Quantity,Tax,Total,Date,Time,Payment,Rating
0,750-67-8428,A,1,0,0,Normal,Male,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08:00,Ewallet,9.1
1,226-31-3081,C,0,1,0,Normal,Male,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00,Cash,9.6
2,631-41-3108,A,1,0,0,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23:00,Credit card,7.4
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:30:00,Ewallet,8.4
4,373-73-7910,A,1,0,0,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00,Ewallet,5.3

clean the date column

In [77]:
df['Date']=pd.to_datetime(df['Date'])
df.head()

,Invoice_ID,Branch,Yangon,Naypyitaw,Mandalay,Customer_type,Gender,Product_line,Unit_price,Quantity,Tax,Total,Date,Time,Payment,Rating
0,750-67-8428,A,1,0,0,Normal,Male,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,9.1
1,226-31-3081,C,0,1,0,Normal,Male,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,9.6
2,631-41-3108,A,1,0,0,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,7.4
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:30:00,Ewallet,8.4
4,373-73-7910,A,1,0,0,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00,Ewallet,5.3

combine the date and time in one column with datetime format

In [78]:
df['Date_time'] = pd.to_datetime(df['Date']) + pd.to_timedelta(df['Time'].astype(str))
df = df.drop(['Date', 'Time'], axis=1)
df.head()

,Invoice_ID,Branch,Yangon,Naypyitaw,Mandalay,Customer_type,Gender,Product_line,Unit_price,Quantity,Tax,Total,Payment,Rating,Date_time
0,750-67-8428,A,1,0,0,Normal,Male,Health and beauty,74.69,7,26.1415,548.9715,Ewallet,9.1,2019-01-05 13:08:00
1,226-31-3081,C,0,1,0,Normal,Male,Electronic accessories,15.28,5,3.8200,80.2200,Cash,9.6,2019-03-08 10:29:00
2,631-41-3108,A,1,0,0,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,Credit card,7.4,2019-03-03 13:23:00
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,23.2880,489.0480,Ewallet,8.4,2019-01-27 20:30:00
4,373-73-7910,A,1,0,0,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,Ewallet,5.3,2019-02-08 10:37:00

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice_ID     1006 non-null   object
 1   Branch         1006 non-null   object
 2   Yangon         1006 non-null   int64
 3   Naypyitaw      1006 non-null   int64
 4   Mandalay       1006 non-null   int64
 5   Customer_type  1006 non-null   object
 6   Gender         1006 non-null   object
 7   Product_line   1006 non-null   object
 8   Unit_price     1006 non-null   float64
 9   Quantity       1006 non-null   int64
 10  Tax            1006 non-null   float64
 11  Total          1006 non-null   float64
 12  Payment        1006 non-null   object
 13  Rating         1006 non-null   float64
 14  Date_time      1006 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(4), object(6)
memory usage: 118.0+ KB

create a city column that combine the columns 'Yangon','Naypyitaw','Mandalay'

In [81]:
def city(row):
  if row['Yangon'] == 1:
    return 'Yangon'
  elif row['Naypyitaw'] == 1:
    return 'Naypyitaw'
  elif row['Mandalay'] == 1:
    return 'Mandalay'
  else:
    return 'Unknown'

df['City'] = df.apply(city, axis=1)
df = df.drop(['Yangon','Naypyitaw','Mandalay'], axis=1)
df.head()

,Invoice_ID,Branch,Customer_type,Gender,Product_line,Unit_price,Quantity,Tax,Total,Payment,Rating,Date_time,City
0,750-67-8428,A,Normal,Male,Health and beauty,74.69,7,26.1415,548.9715,Ewallet,9.1,2019-01-05 13:08:00,Yangon
1,226-31-3081,C,Normal,Male,Electronic accessories,15.28,5,3.8200,80.2200,Cash,9.6,2019-03-08 10:29:00,Naypyitaw
2,631-41-3108,A,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,Credit card,7.4,2019-03-03 13:23:00,Yangon
3,123-19-1176,A,Normal,Male,Health and beauty,58.22,8,23.2880,489.0480,Ewallet,8.4,2019-01-27 20:30:00,Yangon
4,373-73-7910,A,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,Ewallet,5.3,2019-02-08 10:37:00,Yangon

the data is cleaned and ready to be visualised